environments:
  development:
    kubeContext: kind-sandbox
    values:
      - values/development/values.yaml

  production:
    kubeContext: eks-sandbox 
    values:
      - values/production/values.yaml
---
releases:
  - name: app
    namespace: "app-{{ .Environment.Name }}"
    chart: ./charts/http-server
    values:
      - values/{{ .Environment.Name }}/values.yaml
    installed: true
    atomic: false # Rollback on failure is disabled for learning purposes