deployment:
  name: app
  replicaCount: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  image:
    repository: 846869429016.dkr.ecr.ap-northeast-1.amazonaws.com/eks-sandbox-ecr-repository
    tag: "20251206224539"
  containerPort: 8080
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  nginx:
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCpuUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70
service:
  type: NodePort
  nodePort: 30080
